Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$sourceFiles = @(
    '00_model_closure_status.md'
    '01_symbols_and_objects.md'
    '02_equation_dependency_map.md'
    '03_assumptions_and_scope.md'
    '04_comparative_statics_checklist.md'
    '05_calibration_mapping.md'
    '06_bellman_accounting.md'
    '07_revision_decision_log.md'
    '08_model_closure_audit.md'
    '09_file_layering_rules.md'
    '10_main_appendix_consistency_audit.md'
    '11_proposition_dependency_audit.md'
    '12_calibration_claim_audit.md'
)

$outputPath = Join-Path $PSScriptRoot 'COMBINED_model_closure_notes_for_codex.md'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$lf = [string][char]10
$parts = New-Object System.Collections.Generic.List[string]

$header = '# Combined Model Closure Notes for Codex{0}{0}> Generated deterministically by rebuild_combined.ps1. Do not edit this file directly.{0}> Edit the numbered source notes and rerun the script.' -f $lf
$parts.Add($header)

foreach ($file in $sourceFiles) {
    $path = Join-Path $PSScriptRoot $file
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Missing source note: $path"
    }

    $content = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
    $content = [regex]::Replace($content, "\r\n?", $lf)
    $content = $content.TrimEnd([char[]]@([char]13, [char]10))

    $section = '{0}{0}---{0}{0}<!-- BEGIN: {1} -->{0}{0}{2}{0}{0}<!-- END: {1} -->' -f $lf, $file, $content
    $parts.Add($section)
}

$combined = [string]::Join('', $parts.ToArray()) + $lf
[System.IO.File]::WriteAllText($outputPath, $combined, $utf8NoBom)

Write-Output "Rebuilt: $outputPath"
