[CmdletBinding()]
param([Parameter(Mandatory=$true)][ValidateSet('IN_PROGRESS','READY_FOR_APPROVAL','APPROVED')][string]$ExpectedStatus)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$modelRebuild=Split-Path -Parent $PSScriptRoot;$paperRoot=Split-Path -Parent $modelRebuild;$repoRoot=Split-Path -Parent $paperRoot;$auditRoot=Join-Path $modelRebuild 'audit';$specRoot=Join-Path $modelRebuild 'spec';$sourceRoot=Join-Path $specRoot 'source';$notesRoot=Join-Path $paperRoot 'model_notes'
$formalPath=Join-Path $modelRebuild '11_extensions_not_baseline.tex';$statusPath=Join-Path $notesRoot '00_model_closure_status.md';$symbolsPath=Join-Path $notesRoot '01_symbols_and_objects.md';$dependencyPath=Join-Path $notesRoot '02_equation_dependency_map.md';$assumptionsPath=Join-Path $notesRoot '03_assumptions_and_scope.md';$issuesPath=Join-Path $notesRoot '06_open_issues_log.md';$matrixPath=Join-Path $specRoot 'instruction_traceability_matrix.csv';$gateReportPath=Join-Path $auditRoot 'phase11_gate_report.md';$independentPath=Join-Path $auditRoot 'phase11_independent_isolation_audit.md';$latexLogPath=Join-Path $auditRoot 'build_phase11\phase11_compile_wrapper.log';$pdfPath=Join-Path $auditRoot 'build_phase11\phase11_compile_wrapper.pdf';$jsonPath=Join-Path $auditRoot 'phase11_audit_results.json'
$lockedBase='cd5b6e49608749e0bf32f3d9aa235a84f378347b';$entryCommit='2f124ad1972b089d2e54acc967e4818066fc4308';$checks=[Collections.Generic.List[object]]::new()
function Add-Check{param([string]$Id,[bool]$Passed,[string]$Evidence);$checks.Add([pscustomobject]@{id=$Id;passed=$Passed;evidence=$Evidence})};function Test-Hash{param([string]$Id,[string]$Path,[string]$Expected);$actual=if(Test-Path -LiteralPath $Path -PathType Leaf){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}else{'MISSING'};Add-Check $Id ($actual -eq $Expected) "expected=$Expected actual=$actual"}
foreach($s in @(@('P11-HASH-BASE','MAH_model_rebuild_execution_note_for_Codex.md','F6C11377D71E4E25D40FFB8AC9FE2EA7AA051AD7E123BA7E3A32DBA895342B24'),@('P11-HASH-AMD11','MAH_model_rebuild_amendment_v1.1_for_Codex.md','D76856241E460D31087AB60690E85D5681806E53BD42991F725458727CCD1EA9'),@('P11-HASH-AMD12-IMAGE','MAH_model_rebuild_correction_v1.2.png','1C0035AB49A5FF5C207CB71C1E3F04CFAC4E333BEDDAB73841D2A72F603723E5'),@('P11-HASH-AMD12-TEXT','MAH_model_rebuild_correction_v1.2_transcription.md','06AF48B2D853EA82F7176505D2ACA4D0CBFE06E5DB52C18026308196FE85E48E'))){Test-Hash $s[0] (Join-Path $sourceRoot $s[1]) $s[2]};Test-Hash 'P11-HASH-EFFECTIVE' (Join-Path $specRoot 'MAH_model_rebuild_effective_spec_v1.2.md') '855799897F8D519E9859EBC208DC1590017D2345464CED178E4E078B04CB5666'
$branch=(& git -C $repoRoot branch --show-current).Trim();$head=(& git -C $repoRoot rev-parse HEAD).Trim();$remote=(& git -C $repoRoot rev-parse origin/codex/mah-model-rebuild).Trim();Add-Check 'P11-GIT-BRANCH' ($branch -eq 'codex/mah-model-rebuild') "branch=$branch";Add-Check 'P11-GIT-ENTRY' ($head -eq $entryCommit) "head=$head";Add-Check 'P11-GIT-REMOTE' ($remote -eq $head) "remote=$remote"
$manuscriptDiff=@(& git -C $repoRoot diff --name-only $lockedBase -- paper/manuscript);$zipStatus=@(& git -C $repoRoot status --porcelain=v1 -- paper/collaboration/MAH_model_update_20260717.zip);Add-Check 'P11-MANUSCRIPT-READ-ONLY' ($manuscriptDiff.Count -eq 0) "changed=$($manuscriptDiff -join ';')";Add-Check 'P11-ZIP-ISOLATED' ($zipStatus.Count -eq 0) "count=$($zipStatus.Count)"
foreach($path in @($formalPath,(Join-Path $auditRoot 'phase11_preflight.md'),$independentPath,(Join-Path $auditRoot 'phase11_compile_wrapper.tex'),(Join-Path $auditRoot 'phase11_compile_console.txt'),$latexLogPath,$pdfPath,$symbolsPath,$dependencyPath,$assumptionsPath)){Add-Check ('P11-FILE-'+[IO.Path]::GetFileName($path)) (Test-Path -LiteralPath $path -PathType Leaf) "path=$path"}
$statusText=[IO.File]::ReadAllText($statusPath,[Text.Encoding]::UTF8);$statusNeedle="| 11 Extensions | $($ExpectedStatus -replace '_',' ') |";Add-Check 'P11-STATE-PHASE10' $statusText.Contains('| 10 Empirical mapping | APPROVED |') 'Phase 10 approved';Add-Check 'P11-STATE-PHASE11' $statusText.Contains($statusNeedle) "expected=$statusNeedle";Add-Check 'P11-STATE-PHASE12' $statusText.Contains('| 12 Old-to-new crosswalk | NOT STARTED |') 'Phase 12 not started'
$matrix=Import-Csv -LiteralPath $matrixPath;$expectedApproval=if($ExpectedStatus -eq 'APPROVED'){'YES'}else{'NO'};foreach($id in @('P11-D01','P11-G01')){$row=@($matrix|Where-Object requirement_id -eq $id);$rs=if($row.Count -eq 1){$row[0].current_status}else{'BAD_ROW'};$ra=if($row.Count -eq 1){$row[0].approval_status}else{'BAD_ROW'};Add-Check ('P11-MATRIX-'+$id) ($row.Count -eq 1 -and $rs -eq $ExpectedStatus -and $ra -eq $expectedApproval) "status=$rs approval=$ra"}
$formalText=[IO.File]::ReadAllText($formalPath,[Text.Encoding]::UTF8);$symbolsText=[IO.File]::ReadAllText($symbolsPath,[Text.Encoding]::UTF8);$dependencyText=[IO.File]::ReadAllText($dependencyPath,[Text.Encoding]::UTF8);$assumptionsText=[IO.File]::ReadAllText($assumptionsPath,[Text.Encoding]::UTF8);$independentText=[IO.File]::ReadAllText($independentPath,[Text.Encoding]::UTF8);$issuesText=[IO.File]::ReadAllText($issuesPath,[Text.Encoding]::UTF8)
$blocks=@([regex]::Matches($formalText,'\\subsection\{Extension ([1-6]):'));$nums=@($blocks|ForEach-Object{[int]$_.Groups[1].Value});Add-Check 'P11-BLOCK-COUNT' ($blocks.Count -eq 6 -and ($nums -join ',') -eq '1,2,3,4,5,6') "numbers=$($nums -join ',')"
foreach($needle in @('Smooth route choice','Route-specific implementation','Transfer-market microfoundation','Dynamic firm evolution','Multi-CMO matching','Research-versus-development allocation','Quarantine rule','inactive in the','separate approval','Deterministic','\not\Rightarrow','No Bellman equation','match-level data','implemented here:','not import this')){Add-Check ('P11-FORMAL-'+($needle.GetHashCode().ToString('X8'))) $formalText.Contains($needle) "required=$needle"}
foreach($id in @('P11-X01','P11-X02','P11-X03','P11-X04','P11-X05','P11-X06')){Add-Check ('P11-DEPENDENCY-'+$id) $dependencyText.Contains($id) "required=$id"};Add-Check 'P11-SYMBOL-QUARANTINE' ($symbolsText.Contains('excluded from the 83-row active') -and $symbolsText.Contains('There are 83 active rows.')) 'extension symbols inactive';Add-Check 'P11-ASSUMPTION-QUARANTINE' $assumptionsText.Contains('Phase 11 adds no baseline assumption') 'no baseline assumption';Add-Check 'P11-INDEPENDENT' ($independentText.Contains('Independent review conclusion: no P0 and no P1') -and $independentText.Contains('## 3. Baseline scan')) 'independent audit';Add-Check 'P11-NO-P0' (-not $issuesText.Contains('Phase: Phase 11') -and -not($issuesText -match 'Severity now:.*P0')) 'no Phase 11 P0'
$baselineFiles=1..10|ForEach-Object{$tag='{0:D2}' -f $_;Get-ChildItem -LiteralPath $modelRebuild -Filter ($tag+'_*.tex')|Select-Object -First 1};$baselineText=($baselineFiles|ForEach-Object{[IO.File]::ReadAllText($_.FullName,[Text.Encoding]::UTF8)}) -join [Environment]::NewLine
foreach($pattern in @('P_\{ir\}\^\{\\mathrm\{logit\}\}','U_\{ir\}=W_\{ir\}\+','\\chi\^I\(q,m\)\s*=','\\chi\^E\(q,m\)\s*=','V\([^)]*\)\s*=.*\\max','x_i\^R\s*\+.*x_i\^D')){$m=[regex]::Match($baselineText,$pattern,[Text.RegularExpressions.RegexOptions]::IgnoreCase);Add-Check ('P11-BASELINE-CLEAN-'+($pattern.GetHashCode().ToString('X8'))) (-not $m.Success) "pattern=$pattern match=$($m.Value)"}
$labels=@([regex]::Matches($formalText,'\\label\{([^}]+)\}')|ForEach-Object{$_.Groups[1].Value});$dups=@($labels|Group-Object|Where-Object Count -gt 1);$dupNames=@($dups|ForEach-Object{$_.Name});Add-Check 'P11-LABEL-UNIQUE' ($dups.Count -eq 0) "duplicates=$($dupNames -join ';')";$logText=if(Test-Path -LiteralPath $latexLogPath){[IO.File]::ReadAllText($latexLogPath,[Text.Encoding]::UTF8)}else{''};$fatal=@(@('! LaTeX Error:','Fatal error occurred','There were undefined references','multiply defined')|Where-Object{$logText.Contains($_)});$boxes=@([regex]::Matches($logText,'(?m)^(Overfull|Underfull) \\[hv]box')).Count;Add-Check 'P11-LATEX-FATAL' ($fatal.Count -eq 0 -and $logText.Length -gt 0) "fatal=$($fatal -join ';')";Add-Check 'P11-LATEX-BOXES' ($boxes -eq 0) "box_warnings=$boxes"
$allowed=@('paper/model_notes/00_model_closure_status.md','paper/model_notes/01_symbols_and_objects.md','paper/model_notes/02_equation_dependency_map.md','paper/model_notes/03_assumptions_and_scope.md','paper/model_rebuild/.gitattributes','paper/model_rebuild/11_extensions_not_baseline.tex','paper/model_rebuild/audit/phase11_artifact_hashes.md','paper/model_rebuild/audit/phase11_audit_results.json','paper/model_rebuild/audit/phase11_commit_manifest.txt','paper/model_rebuild/audit/phase11_compile_console.txt','paper/model_rebuild/audit/phase11_compile_wrapper.tex','paper/model_rebuild/audit/phase11_gate_report.md','paper/model_rebuild/audit/phase11_independent_isolation_audit.md','paper/model_rebuild/audit/phase11_preflight.md','paper/model_rebuild/scripts/audit_phase11.ps1','paper/model_rebuild/spec/approvals/phase11_standing_authorization.md','paper/model_rebuild/spec/instruction_traceability_matrix.csv','paper/model_rebuild/spec/specification_hashes.md');$set=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);foreach($p in $allowed){[void]$set.Add($p)};$unexpected=[Collections.Generic.List[string]]::new();foreach($line in @(& git -C $repoRoot status --porcelain=v1 --untracked-files=all)){if([string]::IsNullOrWhiteSpace($line)){continue};$p=$line.Substring(3).Replace('\','/');if(-not $set.Contains($p)){$unexpected.Add($p)}};Add-Check 'P11-SCOPE-EXACT' ($unexpected.Count -eq 0) "unexpected=$($unexpected -join ';')"
if($ExpectedStatus -in @('READY_FOR_APPROVAL','APPROVED')){$gate=if(Test-Path -LiteralPath $gateReportPath){[IO.File]::ReadAllText($gateReportPath,[Text.Encoding]::UTF8)}else{''};$ids=@('RL-01','RL-28','P11-D01','P11-G01','QA-PROOF-10','QA-ECON-01','QA-ECON-02','QA-ECON-03','QA-ECON-05','QA-ECON-07');$missing=@($ids|Where-Object{-not $gate.Contains($_)});Add-Check 'P11-GATE-IDS' ($missing.Count -eq 0) "missing=$($missing -join ';')";Add-Check 'P11-GATE-RESULT' ($gate.Contains('P0: 0') -and $gate.Contains('Overall gate: PASS')) 'gate PASS'}
$failed=@($checks|Where-Object{-not $_.passed});$result=[ordered]@{phase=11;expected_status=$ExpectedStatus;status=if($failed.Count -eq 0){$ExpectedStatus}else{'AUDIT_FAILED'};generated_at=(Get-Date).ToString('o');passed=@($checks|Where-Object passed).Count;failed=$failed.Count;checks=$checks};[IO.File]::WriteAllText($jsonPath,($result|ConvertTo-Json -Depth 6)+[Environment]::NewLine,[Text.UTF8Encoding]::new($false));Write-Output "SUMMARY status=$($result.status) passed=$($result.passed) failed=$($result.failed) report=$jsonPath";foreach($i in $failed){Write-Output "FAIL $($i.id): $($i.evidence)"};if($failed.Count -gt 0){exit 1}
