import PptxGenJS from "npm:pptxgenjs";
import * as imageHelpers from "./pptxgenjs_helpers/image.js";
const { imageSizingContain } = imageHelpers;
const pptx = new PptxGenJS();
pptx.defineLayout({ name: "C", width: 10, height: 7.5 });
pptx.layout = "C";
const slide = pptx.addSlide();
slide.addShape("rect", { x: 0.3, y: 0.3, w: 9.4, h: 6.9, fill: { color: "FFFDF9" }, line: { color: "D7D1C5", width: 1 } });
slide.addText("image smoke", { x: 0.6, y: 0.6, w: 3, h: 0.4, fontFace: "Microsoft YaHei", fontSize: 24, bold: true });
slide.addImage({ path: "./extracted_media_white/image3.png", ...imageSizingContain("./extracted_media_white/image3.png", 1, 1.5, 5, 3.5) });
await pptx.writeFile({ fileName: "image_smoke.pptx" });
console.log("image_ok");
