import PptxGenJS from "npm:pptxgenjs";
const pptx = new PptxGenJS();
pptx.defineLayout({ name: "C", width: 10, height: 7.5 });
pptx.layout = "C";
const slide = pptx.addSlide();
slide.addShape("rect", { x: 0.5, y: 0.5, w: 2, h: 1, fill: { color: "FFFFFF" }, line: { color: "000000", width: 1 }, radius: 0.05 });
slide.addShape("roundRect", { x: 3, y: 0.5, w: 2, h: 1, fill: { color: "FFEEEE" }, line: { color: "000000", width: 1 }, radius: 0.1 });
slide.addShape("ellipse", { x: 5.5, y: 0.5, w: 1, h: 1, fill: { color: "EEFFEE", transparency: 20 }, line: { color: "000000", width: 1 } });
slide.addShape("line", { x: 0.5, y: 2, w: 1.5, h: 0, line: { color: "000000", width: 1 } });
slide.addText("shape test", { x: 0.7, y: 2.2, w: 2, h: 0.4, fontFace: "Microsoft YaHei", fontSize: 18 });
await pptx.writeFile({ fileName: "shape_test.pptx" });
console.log("shape_ok");
